use group01;

DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS CreditCards;
DROP TABLE IF EXISTS Reservations;

CREATE TABLE IF NOT EXISTS Rooms (
	CODE VARCHAR(3) NOT NULL PRIMARY KEY,
	Name VARCHAR(30) NOT NULL UNIQUE,
	Num_Beds INT NOT NULL,
	BedType ENUM('King', 'Queen', 'Double') NOT NULL,
	MaxOcc INT NOT NULL,
	BasePrice INT NOT NULL,
	Decor ENUM('modern', 'traditional', 'rustic') NOT NULL 
);

CREATE TABLE IF NOT EXISTS Customers (
	cID INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	LastName VARCHAR(30) NOT NULL,
	FirstName VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS CreditCards (
	CardNum INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	Balance FLOAT NOT NULL,
	CardLimit FLOAT NOT NULL,
	OwnerID INT UNSIGNED NOT NULL,
	FOREIGN KEY (OwnerID) REFERENCES Customers (cID)
);

CREATE TABLE IF NOT EXISTS Reservations (
	rID INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	CheckIn DATE NOT NULL,
	CheckOut DATE NOT NULL,
	Rate FLOAT NOT NULL,
	NumOcc INT NOT NULL,
	RoomCode VARCHAR(3) NOT NULL,
	CustomerID INT UNSIGNED NOT NULL,
	CardNum INT UNSIGNED NOT NULL,
	FOREIGN KEY (RoomCode) REFERENCES Rooms (CODE),
	FOREIGN KEY (CustomerID) REFERENCES Customers (cID),
	FOREIGN KEY (CardNum) REFERENCES CreditCards (CardNum)
);

